In [3]:
using LinearAlgebra
A = [ 2 -1 -1 0; -1 1.5 0 -0.5; -1 0 1.7 -0.2; 0 -0.5 -0.2 1.7 ]   
B = [ 0 0 3 0 ]'

4×1 adjoint(::Matrix{Int64}) with eltype Int64:
 0
 0
 3
 0

In [8]:
A*x = B
x = A\B

4×1 Matrix{Float64}:
 3.0638297872340425
 2.425531914893617
 3.7021276595744683
 1.1489361702127658

In [10]:
svd(A)

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
4×4 Matrix{Float64}:
 -0.721623  -0.225374  -0.252553  0.60389
  0.458236  -0.43194    0.499235  0.595157
  0.477436   0.403686  -0.633069  0.456417
 -0.203308   0.774385   0.534982  0.269793
singular values:
4-element Vector{Float64}:
 3.296621596268449
 1.8746326482479798
 1.4700780624595662
 0.2586676930240056
Vt factor:
4×4 Matrix{Float64}:
 -0.721623   0.458236   0.477436  -0.203308
 -0.225374  -0.43194    0.403686   0.774385
 -0.252553   0.499235  -0.633069   0.534982
  0.60389    0.595157   0.456417   0.269793

In [11]:
inv(A)

4×4 Matrix{Float64}:
 1.6383    1.25532   1.02128   0.489362
 1.25532   1.70213   0.808511  0.595745
 1.02128   0.808511  1.23404   0.382979
 0.489362  0.595745  0.382979  0.808511

In [12]:
det(A)

2.35

In [2]:
B = (1/15) * [14 2; 4 22; 16 13]



3×2 Matrix{Float64}:
 0.933333  0.133333
 0.266667  1.46667
 1.06667   0.866667

In [3]:
using Statistics
std(B)


0.5031751039004068

In [8]:
using LinearAlgebra

# Define the matrix B
B = (1/15) * [14 2;
              4 22;
              16 13]

println("Matrix B =")
println(B)

# Compute the Singular Value Decomposition
U, S, V = svd(B)

println("\nMatrix U =")
println(U)

println("\nMatrix Σ (Sigma) =")
println(Diagonal(S))

println("\nMatrix V =")
println(V)

# Verify decomposition: U * Diagonal(S) * V' ≈ B
println("\nCheck: U * Σ * V' =")
println(U * Diagonal(S) * V')


Matrix B =
[0.9333333333333333 0.13333333333333333; 0.26666666666666666 1.4666666666666666; 1.0666666666666667 0.8666666666666667]

Matrix U =
[-0.33333333333333365 0.6666666666666669; -0.6666666666666666 -0.666666666666667; -0.6666666666666669 0.3333333333333332]

Matrix Σ (Sigma) =
Diagonal([2.0, 0.9999999999999999])

Matrix V =
[-0.6000000000000001 0.8; -0.8 -0.6000000000000001]

Check: U * Σ * V' =
[0.9333333333333338 0.13333333333333378; 0.2666666666666665 1.4666666666666668; 1.0666666666666669 0.8666666666666671]


In [10]:
# Matrix-vector multiplication performance comparison

# Function to perform matrix-vector multiplication using loops
function matvec_loops(A, x)
    n = size(A, 1)
    b = zeros(n)
    for j in 1:n
        for i in 1:n
            b[i] += A[i, j] * x[j]
        end
    end
    return b
end

# Function to perform matrix-vector multiplication using built-in method
function matvec_builtin(A, x)
    return A * x
end

# Run experiments for three different sizes
for n in [3, 10, 100]
    println("---------------------------------------------------")
    println("Matrix size: $n x $n")
    
    A = rand(n, n)
    x = rand(n)
    
    println("Using built-in method:")
    @time b1 = matvec_builtin(A, x)
    
    println("Using loops:")
    @time b2 = matvec_loops(A, x)
    
    # Check if both results are the same
    println("Are results equal? ", isapprox(b1, b2))
end


---------------------------------------------------
Matrix size: 3 x 3
Using built-in method:
  0.001889 seconds (2 allocations: 80 bytes)
Using loops:
  0.000003 seconds (2 allocations: 80 bytes)
Are results equal? true
---------------------------------------------------
Matrix size: 10 x 10
Using built-in method:
  0.000006 seconds (2 allocations: 144 bytes)
Using loops:
  0.000003 seconds (2 allocations: 144 bytes)
Are results equal? true
---------------------------------------------------
Matrix size: 100 x 100
Using built-in method:
  0.000009 seconds (2 allocations: 928 bytes)
Using loops:
  0.000014 seconds (2 allocations: 928 bytes)
Are results equal? true


In [11]:
using LinearAlgebra

# Define the original matrix B
B = (1/15) * [14 2;
               4 22;
               16 13]

# Define U matrix
U = [1/3   2/3  -2/3;
     2/3  -2/3  -1/3;
     2/3   1/3   2/3]

# Define Sigma matrix (3x2)
Σ = [2 0;
     0 1;
     0 0]

# Define V matrix
V = (1/5) * [3  -4;
             4   3]

# Reconstruct B using SVD
B_reconstructed = U * Σ * transpose(V)

# Check if reconstruction is correct
println("Original B:")
println(B)
println("\nReconstructed B from SVD:")
println(B_reconstructed)

# Compute the difference
diff = B - B_reconstructed
println("\nDifference (B - UΣVᵀ):")
println(diff)

# Check norm of the difference
println("\nNorm of difference: ", norm(diff))


Original B:
[0.9333333333333333 0.13333333333333333; 0.26666666666666666 1.4666666666666666; 1.0666666666666667 0.8666666666666667]

Reconstructed B from SVD:
[-0.1333333333333333 0.9333333333333333; 1.3333333333333335 0.6666666666666666; 0.5333333333333333 1.2666666666666666]

Difference (B - UΣVᵀ):
[1.0666666666666667 -0.8; -1.0666666666666669 0.7999999999999999; 0.5333333333333333 -0.3999999999999999]

Norm of difference: 2.0


In [13]:
# Question 5 - Checking Results in Julia
# Matrix–Vector multiplication two ways

# (1) Using loops
function matvec_loops(A, x)
    n = size(A, 1)
    b = zeros(n)
    for j in 1:n
        for i in 1:n
            b[i] += A[i, j] * x[j]
        end
    end
    return b
end

# (2) Built-in matrix–vector multiplication
function matvec_builtin(A, x)
    return A * x
end

# Run experiments for different matrix sizes
for n in [3, 10, 100]
    println("---------------------------------------------------")
    println("Matrix size: $n x $n")
    A = rand(n, n)
    x = rand(n)

    println("\nUsing built-in method:")
    @time b1 = matvec_builtin(A, x)

    println("\nUsing loops:")
    @time b2 = matvec_loops(A, x)

    println("\nResults are equal? ", isapprox(b1, b2))
end


---------------------------------------------------
Matrix size: 3 x 3

Using built-in method:
  0.001120 seconds (2 allocations: 80 bytes)

Using loops:
  0.000002 seconds (2 allocations: 80 bytes)

Results are equal? true
---------------------------------------------------
Matrix size: 10 x 10

Using built-in method:
  0.000005 seconds (2 allocations: 144 bytes)

Using loops:
  0.000002 seconds (2 allocations: 144 bytes)

Results are equal? true
---------------------------------------------------
Matrix size: 100 x 100

Using built-in method:
  0.000017 seconds (2 allocations: 928 bytes)

Using loops:
  0.000008 seconds (2 allocations: 928 bytes)

Results are equal? true


In [17]:

using LinearAlgebra

A = [1 4 7;
     2 5 8;
     3 6 9]
det_A = det(A)


0.0

In [16]:

using LinearAlgebra

A = [2 1 1;
     2 2 -1;
     4 -1 6]
det_A = det(A)

-4.0000000000000036

In [19]:

A = [2 1 1;
     2 2 -1;
     4 -1 6]
b=[9 0 -2]'

3×1 adjoint(::Matrix{Int64}) with eltype Int64:
  9
  0
 -2

In [20]:
X = A\b

3×1 Matrix{Float64}:
 -26.24999999999998
  37.999999999999964
  23.49999999999998

In [23]:
L= [ 1 0 0; 1  1 0; 2 3 1] 
U= [ 2 1 1; 0 1 -2; 0 0 -2]

3×3 Matrix{Int64}:
 2  1   1
 0  1  -2
 0  0  -2

In [24]:
L*U

3×3 Matrix{Int64}:
 2  1   1
 2  2  -1
 4  5  -6

In [25]:

A = [2 1 1;
     2 2 -1;
     4 -1 6]
b=[9 0 -2]'

3×1 adjoint(::Matrix{Int64}) with eltype Int64:
  9
  0
 -2

In [28]:
X = A\b

3×1 Matrix{Float64}:
 -26.24999999999998
  37.999999999999964
  23.49999999999998

In [33]:
X = L

3×3 Matrix{Int64}:
 1  0  0
 1  1  0
 2  3  1

In [34]:
X = U

3×3 Matrix{Int64}:
 2  1   1
 0  1  -2
 0  0  -2

In [35]:
A = L*U

3×3 Matrix{Int64}:
 2  1   1
 2  2  -1
 4  5  -6